### ISSUE TITLE
UCM-captions 的BLEU-1到4评估是否正确？

### ISSUE THREAD

**Issue by Czi24** [ZhanYang-nwpu/SkyEyeGPT#4]
<img width="824" alt="截屏2024-03-25 19 56 08" src="https://github.com/ZhanYang-nwpu/SkyEyeGPT/assets/164003022/c9e5fef5-90ad-4eb5-8dc7-7c0c07fb20e5">

![image](https://github.com/ZhanYang-nwpu/SkyEyeGPT/assets/164003022/a5279640-14ed-4ab7-b35c-90e35ee59836)

请问是否会公开评估的代码，BLEU-1到4太高了呀

**Comment by ZhanYang-nwpu** [comment]
> <img alt="截屏2024-03-25 19 56 08" width="824" src="https://private-user-images.githubusercontent.com/164003022/316491332-c9e5fef5-90ad-4eb5-8dc7-7c0c07fb20e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjgzNzcsIm5iZiI6MTcxMTM2ODA3NywicGF0aCI6Ii8xNjQwMDMwMjIvMzE2NDkxMzMyLWM5ZTVmZWY1LTkwYWQtNGViNS04ZGM3LTdjMGMwN2ZiMjBlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMjAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JkYjk0YjBmYjZhYWQ3ZTUzODEzNDE4MDg2YmFlMjBiYjE2MTMyYTQ2YmM1MmY5YTI0NjlhMGIzYzdmYjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZFb0roHwyagNPXVRTjroxa1DtNBGKW4vEPMEi_9kaUQ">
> ![image](https://private-user-images.githubusercontent.com/164003022/316491512-a5279640-14ed-4ab7-b35c-90e35ee59836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjgzNzcsIm5iZiI6MTcxMTM2ODA3NywicGF0aCI6Ii8xNjQwMDMwMjIvMzE2NDkxNTEyLWE1Mjc5NjQwLTE0ZWQtNGFiNy1iMzVjLTkwZTM1ZWU1OTgzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMjAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDY5NjVhM2MzYzg2OGYzZWFhZGY5OTk2YzA3ODgzYWYyYjNkNGRjZmY2YjYxYmFlYzljOWRjZmIyNjk1YTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s23EvjaRFSCplx-0KGAGozt7mzOMoGNDbRGbvwiuLkE)
> 
> 请问是否会公开评估的代码，BLEU-1到4太高了呀



我们会公开所有的评估代码

We will make all the evaluation code publicly available.
